name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        openwrt_revision: ["v25.12.0-rc1"]
        openwrt_target: ["lantiq-xrx200"]

    env:
      OPENWRT_REPO_URL: "https://github.com/openwrt/openwrt.git"
      OPENWRT_REVISION: ${{ matrix.openwrt_revision }}
      OPENWRT_TARGET: ${{ matrix.openwrt_target }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: set cache key
        run: echo "CACHE_KEY=${{ matrix.openwrt_target }}-${{ matrix.openwrt_revision }}-${{ hashFiles(format('configs/config-{0}', matrix.openwrt_target), 'patches/*') }}" >>"$GITHUB_ENV"

      - name: install prerequisites
        run: ./1-prerequisites.sh

      - name: restore repository cache
        id: restore-repository
        uses: actions/cache/restore@v5
        with:
          path: openwrt
          key: repository-${{ env.CACHE_KEY }}

      - name: clone repository
        if: steps.restore-repository.outputs.cache-hit != 'true'
        run: ./2-repository.sh

      - name: save repository cache
        if: steps.restore-repository.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: openwrt
          key: ${{ steps.restore-repository.outputs.cache-primary-key }}

      - name: restore download cache
        id: restore-download
        uses: actions/cache/restore@v5
        with:
          path: openwrt/dl
          key: download-${{ env.CACHE_KEY }}

      - name: download dependencies
        if: steps.restore-download.outputs.cache-hit != 'true'
        run: ./3-download.sh

      - name: save download cache
        if: steps.restore-download.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: openwrt/dl
          key: ${{ steps.restore-download.outputs.cache-primary-key }}

      - name: restore toolchain cache
        id: restore-toolchain
        uses: actions/cache/restore@v5
        with:
          path: |
            openwrt/build_dir
            openwrt/staging_dir
          key: toolchain-${{ env.CACHE_KEY }}

      - name: compile toolchain
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        run: ./4-toolchain.sh

      - name: save toolchain cache
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: |
            openwrt/build_dir
            openwrt/staging_dir
          key: ${{ steps.restore-toolchain.outputs.cache-primary-key }}

      - name: compile
        run: ./5-compile.sh

      - name: save apks
        uses: actions/upload-artifact@v6
        with:
          name: apks
          path: openwrt/bin/packages/*/base/dnsmasq*.apk
