name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        openwrt_revision: ["v25.12.0-rc1"]
        openwrt_target: ["lantiq-xrx200"]

    env:
      OPENWRT_REPO_URL: "https://github.com/openwrt/openwrt.git"
      OPENWRT_REVISION: ${{ matrix.openwrt_revision }}
      OPENWRT_TARGET: ${{ matrix.openwrt_target }}

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install prerequisites
        run: ./1-prerequisites.sh

      - name: restore repository cache
        id: restore-repository
        uses: actions/cache/restore@v5
        with:
          path: openwrt
          key: repository-${{ matrix.openwrt_target }}-${{ matrix.openwrt_revision }}-${{ hashFiles(format('configs/config-{0}', matrix.openwrt_target), 'patches/*') }}

      - name: clone repositories
        if: steps.restore-repository.outputs.cache-hit != 'true'
        run: ./2-repository.sh

      - name: patch
        if: steps.restore-repository.outputs.cache-hit != 'true'
        run: ./3-patch.sh

      - name: configure
        if: steps.restore-repository.outputs.cache-hit != 'true'
        run: ./4-config.sh

      - name: save repository cache
        if: steps.restore-repository.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: openwrt
          key: ${{ steps.restore-repository.outputs.cache-primary-key }}

      - name: restore download cache
        id: restore-download
        uses: actions/cache/restore@v5
        with:
          path: openwrt/dl
          key: download-${{ matrix.openwrt_target }}-${{ matrix.openwrt_revision }}-${{ hashFiles(format('configs/config-{0}', matrix.openwrt_target), 'patches/*') }}

      - name: download dependencies
        if: steps.restore-download.outputs.cache-hit != 'true'
        run: ./5-download.sh

      - name: save download cache
        if: steps.restore-download.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: openwrt/dl
          key: ${{ steps.restore-download.outputs.cache-primary-key }}

      - name: restore toolchain cache
        id: restore-toolchain
        uses: actions/cache/restore@v5
        with:
          path: openwrt/staging_dir
          key: toolchain-${{ matrix.openwrt_target }}-${{ matrix.openwrt_revision }}-${{ hashFiles(format('configs/config-{0}', matrix.openwrt_target), 'patches/*') }}

      - name: compile / install toolchain
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        run: ./6-toolchain.sh

      - name: save toolchain cache
        if: steps.restore-toolchain.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: openwrt/staging_dir
          key: ${{ steps.restore-toolchain.outputs.cache-primary-key }}

      - name: compile
        run: ./7-compile.sh

      - name: save dnsmasq apks
        uses: actions/upload-artifact@v6
        with:
          name: dnsmasq
          path: openwrt/bin/packages/*/base/dnsmasq*.apk
